ani1609/Spendwise

- client/package-lock.json
- client/package.json
- client/src/components/ExpenseTracker.js
- client/src/components/TransactionLoading.js
Fixes #105 
Added a loading skeleton when transactions are loading.
> Enhanced Loading Screen for transactions loading

- client/src/components/DoughnutChart.js
Added padding and slightly Scaled up chart and scaled down for better readability. Please leave comments if unsatisfied.
Before:
After:
> Fixed: Lack of padding below the expense chart #87

- client/src/components/DoughnutChart.js
- client/src/components/ExpenseTracker.js
Fixes #123 
Here is the working demo of the feature I implemented:
https://github.com/ani1609/Spendwise/assets/64408989/377bc457-a662-436a-8dce-5b5455fb7464
Here is how I did it:
1. Created a new state for selected category
2. The following line is used to update the state variable selectedCategory with the category of the transaction being edited.
3. The following line is added to the Firestore query used in the handleDelete function. This addition ensures that when a user deletes a transaction, the deletion is specific to both the transaction ID and the selected category.
4. A handleCategory function created to filter data based on category.
5. Dropdown created for users to select categories
> feat:filter by category feature added

- client/src/styles/Navbar.css
/* padding to 30px for screen widths<=768px */
@media only screen and (max-width: 768px) {
.navbar_parent {
padding: 0px 30px;
}
.navbar_parent h1 {
font-size: 30px;
}
.profile_container {
gap: 10px;
}
.profile_container h4 {
font-size: 16px;
}
.login_signup_container {
gap: 10px;
}
.login_signup_container button {
height: 30px;
width: 80px;
font-size: 15px;
}
} added this line
> Padding to 30px for screen widths<=768px

- client/src/styles/Navbar.css
- Modified Navbar.css to enhance responsiveness.
- Updated font sizes and spacing in different media queries.
- Tested the changes on various devices and browsers.
- Ran unit tests for affected components.
- Conducted manual testing on mobile and desktop devices.
- Verified that the changes did not introduce regressions.
> Update Responsive Styles for Navbar

- client/src/styles/Navbar.css
> Login-signup buttons overlapping

- client/src/components/Login.js
- client/src/components/Signup.js
> Revert "signup/login button fix"

- client/src/components/Signup.js
- client/src/styles/Login.css
- client/src/styles/Signup.css
> UI fix #164 made Login and Signup modal and input same width

- client/src/styles/Login.css
- client/src/styles/Signup.css
> minor bug fixes

- client/src/components/ExpenseTracker.js
Fixes #151 
Added styles to filter forms. Borders added ,layout corrected.
**Checklist:**
https://github.com/ani1609/Spendwise/assets/64408989/bb470994-f14c-4b1d-b1ea-cade59961762
> filter forms styled

- client/src/components/ExpenseTracker.js
- client/src/styles/ExpenseTracker.css
Fixed uneven color with UI
Fixes #154
Changed color of the button using tailwindcss, and aligned them center for easy usage. Also aligned the form title to the center for readability.
**Checklist:**
Desktop:
Tablet:
Mobile:
> Fixed: Uneven Color for "New" button

- client/src/components/ExpenseTracker.js
Fixes #184 
Cursor type pointer is visible when hovered on type and category filter in transactions section.
**Checklist:**
> FIX: cursor pointer on transaction filters

- client/package-lock.json
- client/package.json
- client/src/components/Signup.js
- client/src/styles/Signup.css
Fixes #181 
Added a button 'Continue with Google' below Signup button, styled using TailwindCSS.
**Checklist:**
> 'Continue with Google' button added in Signup.js

- client/src/components/Login.js
- client/src/components/Signup.js
- client/src/styles/Login.css
- client/src/styles/Signup.css
Fixes #173 
Implemented a loading state to indicate whether a login/signup process is ongoing. Utilized conditional rendering to display a spinner until the process completes after a user click. The spinner is styled with the primary color to seamlessly integrate with the website's accent, ensuring a cohesive visual experience.
All the edge cases have been handled.
**Checklist:**
Here are the recordings
https://github.com/ani1609/Spendwise/assets/64408989/639309f2-64d0-4d28-b3fc-5143c024c8b4
https://github.com/ani1609/Spendwise/assets/64408989/2599f005-bdb8-4cb3-8b30-188b1ad28521
https://github.com/ani1609/Spendwise/assets/64408989/135b1c3a-c6e4-4222-b4e3-bd164fc07e57
https://github.com/ani1609/Spendwise/assets/64408989/3276552c-bcbb-48b8-9ff5-5916c92a3114 …
> sign up login loading animation added

- client/src/components/Signup.js
fix issue #189 
add the necessary css for the animation delay of button
**Checklist:**
https://github.com/ani1609/Spendwise/assets/102755411/bd0e6673-13de-4051-872b-4c3a3ebb71b6
> fix: animation delay time of button

- client/package-lock.json
- client/src/components/ExpenseTracker.js
The border for category and date is fixed to sync with UI.
Fixes #177 
Added tailwind classes similar to UI in these sections.
**Checklist:**
Firefox: 
Fix:
Small screen size:
> Fixing border to sync with UI #177

- client/src/components/profile/PredefinedTransactions.js
- client/src/components/profile/Profile.js
- client/src/components/profile/RightDashboard.js
- client/src/components/profile/Sidebar.js
Fixes #213 
Made Profile page responsive and hamburger menu created
**Checklist:**
> hamburger created for profile page

- client/src/components/Login.js
Fixes #216 
Login page for when click the login button it was not setting the button to disable and sending unwanted request so the fix is to use disabled property of html and change the cursor to not-allowed
**Checklist:**
> Sending unwanted request to the server for login

- client/src/components/profile/Profile.js
- client/src/components/profile/Sidebar.js
Fixes #215 
Profile.js component overlapping problem solved
**Checklist:**
https://github.com/ani1609/Spendwise/assets/64408989/27d69268-1c71-4347-b477-1a49bb5c6d85
> overlapping problem solved

- client/src/styles/ExpenseTracker.css
> minor ui tweaks

- client/src/components/Signup.js
Fixes #217
signup page for when click the signup button it was not setting the button to disable and sending unwanted request so the fix is to use disabled property of html and change the cursor to not-allowed
**Checklist:**
> Sending unwanted request to the server for signup

- client/src/components/Login.js
- client/src/components/Signup.js
- client/src/styles/Login.css
- client/src/styles/Signup.css
> login signup forms ui tweak

- client/src/components/ExpenseTracker.js
- client/src/components/Transactions.js
Fixes #133
Created a separate component Transaction.js that renders the Transactions in the Expense Tracker. Shifted edit, delete and filtering logic to the newly created component. No change has been made in UI/design.
**Checklist:**
> Refactoring code to create separate Transaction component

- client/.eslintrc.json
- client/package-lock.json
- client/package.json
- client/src/components/App.js
- client/src/components/DoughnutChart.js
- client/src/components/ExpenseTracker.js
- client/src/components/Login.js
- client/src/components/Navbar.js
- client/src/components/NoUser.js
- client/src/components/Signup.js
- client/src/components/TransactionLoading.js
- client/src/components/Transactions.js
- client/src/components/profile/PredefinedTransactions.js
- client/src/components/profile/PredefinedTransactionsCards.js
- client/src/components/profile/Profile.js
- client/src/components/profile/RightDashboard.js
- client/src/components/profile/Sidebar.js
- client/src/firebaseConfig.js
- client/src/index.js
- client/tailwind.config.js
- server/.eslintrc.json
- server/configDB/mongoDB.js
- server/controllers/userController.js
- server/index.js
- server/models/user.js
- server/package-lock.json
- server/package.json
Fixes #244 
set up eslint for client and server, along with scripts in package.json
**Checklist:**
> Eslint setup for both client and server

- client/src/components/Transactions.js
#175 
Fixes #175 
Customised category filter menu option
**Checklist:**
> FILTER UI TWEAK: Change the Ui of the category drop down menu of filter

- client/package-lock.json
- client/src/styles/ExpenseTracker.css
> Added a scroll bar

- client/src/components/ExpenseTracker.js
- client/src/components/TransactionForm.js
Fixes #241 
Created a separate component TransactionForm.js that renders the Transactions Form within the Expense Tracker. Shifted input handling and form submission logic to TransactionForm component. Common state variables in TransactionForm.js and Transactions.js have been retained in the ExpenseTracker component itself.
**Checklist:**
I have attached a video demonstrating the working of the form post code refactoring
https://github.com/ani1609/Spendwise/assets/92589912/651bc677-a414-4c87-bdb0-e355a0e04256
> Refactoring code to create separate Transaction Form component

- client/package-lock.json
- client/src/components/ExpenseTracker.js
- client/src/components/Navbar.js
> token validtion error fix

- server/controllers/userController.js
- server/package-lock.json
- server/package.json
**Issue**
While signing up, invalid email formats were not being handled correctly.
Added Zod validation for email to ensure correct format during signup.
Implemented a structured error response with HTTP status code 400 for invalid emails.
Enhanced error message clarity and consistency with best practices.
**Checklist:**
- I have tested my changes.
- My code follows the project's coding standards.
If the user enters email in wrong format, ie. test@gmail, test@a or something, the user will see this:
The user requires to enter the mail in correct format ie test@gmail.co or com or something test@(something).(something like co, com, in etc)
> Added validation for email while signing up.

- client/src/components/Signup.js
> email validation error fix

- server/models/user.js
- server/package-lock.json
- server/package.json
> uninstalling joi

- client/src/components/Login.js
- client/src/components/Navbar.js
- client/src/components/Signup.js
- client/src/firebaseConfig.js
Fixes #190 
Implemented continue with google on Login and Signup Components
**Checklist:**
https://github.com/ani1609/Spendwise/assets/64408989/ecc4c6cd-6f06-46b2-a007-942864098d0c
> google authentication done

- client/src/components/App.js
- client/src/components/ExpenseTracker.js
- client/src/components/Navbar.js
> bug fixes and code optimisations

- client/src/components/Login.js
- client/src/components/Signup.js
> manual login signup bug fux

- client/src/index.css
- client/src/styles/ExpenseTracker.css
> scrollbar ui tweaks

- client/src/components/profile/PredefinedTransactions.css
- client/src/components/profile/PredefinedTransactions.js
- client/src/components/profile/Sidebar.js
Fixes #228 
Developed a new form inside PredefinedTransactions.js which gets opened when add new transactions button is clicked and closes when close button is clicked.
**Checklist:**
https://github.com/ani1609/Spendwise/assets/64408989/68bc6d1f-bd8d-4240-ba24-7e1cca19c379
> Add transaction form#228

- client/src/components/Transactions.js
[#275](https://github.com/ani1609/Spendwise/issues/275)
#275
change icon bg colour and fill in dark mode to #335467 & rgba(19,43,57,1) respectively 
**Checklist:**
before
after
> change icon colors in dark mode

- client/src/components/App.js
- client/src/components/Navbar.js
- client/src/components/TransactionLoading.js
- client/src/index.css
- client/src/styles/App.css
- client/src/styles/ExpenseTracker.css
- client/src/styles/Navbar.css
References #238  
i added global variables --primary,--border,--icons used to style the website's colors. As seen in the second screenshot the colors match those of the first one that shows figma as it was asked in the issue. Login/signup page also adjusted to match the blue theme(third screenshot). The other page (4th screenshot) was left untouched. 
The changes i made apply to light mode. 
Since changes are style-related/css mostly they don't break the websites functionality.
Note: some format changes in the src code (placement of {} and some \n and spaces) have happened due to Prettier-formatter autoformatting.
**Checklist:**
> Adds global CSS variables and changes website's color

- client/src/components/TransactionForm.js
> transactionForm select tag bug ressolved

- client/src/components/App.js
- client/src/components/ExpenseTracker.js
- client/src/components/TransactionForm.js
- client/src/components/Transactions.js
- client/src/components/profile/PredefinedTransactions.js
- client/src/components/profile/RightDashboard.js
- client/src/components/profile/Sidebar.js
- client/src/index.css
- client/src/styles/ExpenseTracker.css
Related Issues:
https://github.com/ani1609/Spendwise/issues/274#event-11348753148
https://github.com/ani1609/Spendwise/issues/274
Description:
added smooth transition from light-mode to dark-mode
Checklist:
I have tested my changes.
My code follows the project's coding standards.
I have updated the documentation (if applicable).
Screenshots:
before
https://github.com/ani1609/Spendwise/issues/274#issue-2057769849
after
https://github.com/ani1609/Spendwise/assets/13862160/c7505506-8722-46a1-be18-88fd4ac77883
> added smooth dark mode transition

- client/src/components/Transactions.js
[#278](https://github.com/ani1609/Spendwise/issues/278)
#278
changed the color of the hr element in dark mode
**Checklist:**
before
after
> hr element color change

- client/src/components/Transactions.js
On Dark theme the transaction filters now have a background color of #011019
#297 
**Checklist:**
> Changed the background color of the transaction filters

- client/src/components/Login.js
- client/src/styles/Login.css
#246 
added a button in the password input field to toggle hiding password or not
**Checklist:**
> Made a toggle to show password on login page

- client/src/components/DoughnutChart.js
Fixes #280 
Changed the border colour of the pie chart in dark mode 
**Checklist:**
> Change border colour in dark mode

- client/src/components/Transactions.js
Changed the background color as requested - see screenshot below:
> change background color of transactions

- client/src/index.css
[#281](https://github.com/ani1609/Spendwise/issues/281#event-11348748686)
#281
successfully changed scrollbar-thumb color to 'rgba(19,43,57,1)' & scrollbar-trackpad color to #959595 for dark-mode
**Checklist:**
before
after
> changed scrollbar color in dark-mode

- client/package-lock.json
- client/src/components/Signup.js
- client/src/styles/Signup.css
issue number : #229 
I have implemented validation of password and name fields.
**Checklist:**
- [yes ] I have tested my changes.
- [ yes] My code follows the project's coding standards.
I have worked on this under KWOC 2023.
> Implementing Validation and Error Handling in Signup Form

- client/src/components/TransactionForm.js
Fixes #317 
fixed weird color change in transaction form
**Checklist:**
https://github.com/ani1609/Spendwise/assets/65119631/a490f4fd-5f29-4ecf-a034-150ff3dc20b8
> fix: transaction form weird color shifts

- client/src/components/Login.js
- client/src/components/Navbar.js
- client/src/components/Signup.js
> email and password absed authentication using firebase authentication

- client/src/components/Transactions.js
- client/src/styles/Transactions.css
> icons colour bug fix

- client/src/components/TransactionForm.js
- client/src/styles/ExpenseTracker.css
> button colour shit bug error

- client/src/components/TransactionForm.js
> button colour bug fix

- client/src/components/App.js
- client/src/components/ErrorPage.js
Added 404 page
Fixes #335
**Checklist:**
Please add KWOC tag!
> Add: Error Page
